test moved from build script to Dockerfile.admin

diff --git a/docker/Dockerfile.admin b/docker/Dockerfile.admin
--- a/docker/Dockerfile.admin
+++ b/docker/Dockerfile.admin
@@ -59,6 +59,12 @@ COPY palace_circulation_admin_ui /opt/circulation/admin
 
 RUN cd /opt/circulation/admin && \
 	npm install && \
+	npm run test-finland && \
+	retval=$? && \
+	if [ $retval -ne 0 ]; then \
+	  echo "Admin UI test failed" && \
+	  exit $retval ; \
+	fi && \
 	mkdir -p /mnt/tarball && \
 	tar czvf /mnt/tarball/admin_dist.tar.gz dist
 
